api:
  enabled: true
  network:
    binding: 0.0.0.0:8080

metrics:
  enabled: true
  queue: metrics
  agent:
    enabled: true
elasticsearch:
  - name: default
    enabled: true
    endpoint: http://localhost:9200
    monitored: false

pipeline:
  - name: ecloud_es_metadata_inject
    auto_start: true
    keep_running: false
    processor:
      - ecloud_es_metadata:
          input:
            schema: http
            es_port: 9200
            es_host_env: "HOSTNAME"
            es_username: "admin"
            auth_file: "/DAT_DIR/.es_auth"
          output:
            elasticsearch: "ecloud_es_name"
  - name: log_collect
    auto_start: true
    keep_running: true
    retry_delay_in_ms: 3000
    processor:
      - es_logs_processor:
          enable: true
          elasticsearch: "ecloud_es_name"
          #update
          logs_path: "/opt/es/elasticsearch-7.7.1/logs"
  - name: ecloud_es_name_node_stats
    auto_start: true
    keep_running: true
    retry_delay_in_ms: 10000
    processor:
      - es_node_stats:
          elasticsearch: ecloud_es_name
  - name: logs_ingest
    auto_start: true
    keep_running: true
    processor:
      - json_indexing:
          index_name: ".infini_logs"
          elasticsearch: "default"
          input_queue: "es_logs"
          idle_timeout_in_seconds: 10
          output_queue:
            name: "es_logs_requests"
            label:
              tag: "logs"
          worker_size: 1
          bulk_size_in_mb: 10
  - name: metrics_ingest
    auto_start: true
    keep_running: true
    processor:
      - json_indexing:
          index_name: ".infini_metrics"
          elasticsearch: "default"
          input_queue: "metrics"
          output_queue:
            name: "metrics_requests"
            label:
              tag: "metrics"
          worker_size: 1
          bulk_size_in_mb: 10

agent:
  major_ip_pattern: ".*"
  labels:
    env: dev
  tags:
    - linux
    - x86
    - es7

skip_instance_detect: true
path.data: /DAT_DIR/infini-agent/data
path.logs: /LOG_DIR/infini-agent/log
agent.manager.endpoint: http://infinilabs-console-0.infinilabs-console.infinilabs.svc.cluster.local:9000