path.data: data
path.logs: log

metrics:
  queue: metrics
  labels:
    env: dev
  tags:
    - linux
    - x86
    - es7
    - v7.5
  network:
    enabled: false
    summary: true
    details: true
#    interfaces:
#      - en0
  memory:
    metrics:
      - swap
      - memory
  disk:
    metrics:
      - ioqs
      - throughput
  cpu:
    metrics:
      - idle
      - system
      - user
      - iowait
      - load
  elasticsearch:
    enabled: true
    node_stats: true


elasticsearch:
  - name: dev
    enabled: true
    schema: http
    monitored: true
    hosts:
      - 192.168.3.188:9299
  - name: 714
    enabled: true
    schema: http
    monitored: true
    hosts:
      - 192.168.3.188:9206

pipeline:
  - name: metrics_ingest
    auto_start: true
    keep_running: true
    processor:
      - json_indexing:
          index_name: ".infini-search-center-metrics"
          elasticsearch: "dev"
          input_queue: "metrics"
          worker_size: 1
          bulk_size_in_mb: 10