path.data: data
path.logs: log
#log.level: trace
#log.debug: true


metrics:
  enabled: true
  major_ip_pattern: "192.*"
  queue: metrics
  labels:
    env: dev
  tags:
    - linux
    - x86
    - es7
    - v7.5
  network:
    enabled: true
    summary: true
    details: true
#    interfaces:
#      - en0
  memory:
    metrics:
      - swap
      - memory
  disk:
    metrics:
      - ioqs
      - throughput
  cpu:
    metrics:
      - idle
      - system
      - user
      - iowait
      - load
  elasticsearch:
    enabled: false
    node_stats: true
    index_stats: true

elasticsearch:
  - name: default
    enabled: true
    endpoint: http://192.168.3.188:9206
    monitored: false
    discovery:
      enabled: true
#    cluster_settings_check: false
#    hosts:
#      - 192.168.3.4:9200
#      - 192.168.3.22:9200
#      - localhost:9100
#  - name: 714
#    enabled: true
#    schema: http
#    monitored: true
#    hosts:
#      - 192.168.3.188:9206



pipeline:
  - name: metrics_ingest
    auto_start: true
    keep_running: true
    processor:
      - json_indexing:
          index_name: ".infini_metrics"
          elasticsearch: "default"
          input_queue: "metrics"
          worker_size: 1
          bulk_size_in_mb: 10
  - name: consume-metrics_requests
    auto_start: true
    keep_running: true
    processor:
      - bulk_indexing:
          bulk:
            compress: true
            batch_size_in_mb: 10
            batch_size_in_docs: 5000
          consumer:
            fetch_max_messages: 100
          queues:
            type: indexing_merge
          when:
            cluster_available: [ "default" ]


agent:
  version: 0.1
  tls: false
  console:
    name: dev
    host: 192.168.3.201
    port: 9000
    tls: false

api:
   enabled: true
   network:
    binding: 0.0.0.0:8080

nodemetric:
  enabled: true
  interval: 10 #second