api:
  enabled: true
  network:
    binding: 0.0.0.0:8080

metrics:
  enabled: true
  queue: metrics
  network:
    enabled: true
    summary: true
    details: true
  memory:
    metrics:
      - swap
      - memory
  disk:
    metrics:
      - iops
      - usage
  cpu:
    metrics:
      - idle
      - system
      - user
      - iowait
      - load
  agent:
    enabled: true
  elasticsearch:
    enabled: true
    agent_mode: true
    node_stats: true
    index_stats: true
    cluster_stats: true

elasticsearch:
  - name: default
    enabled: true
    endpoint: http://localhost:9215
    monitored: false
    discovery:
      enabled: true

pipeline:
  - name: log_collect
    auto_start: true
    keep_running: true
    processor:
      - logs_processor:
          enable: true
  - name: prospector_node
    auto_start: true
    keep_running: true
    processor:
      - prospector:
         decrypt_auth:
           enable: true
           path: "/Users/chengkai/Downloads/es_auth"
           enc_key: "3765323063323065613735363432333161373664643833616331636637303133"
           enc_iv: "66382f4e654c734a2a732a7679675640"
           enc_type: "-aes-256-cbc"
  - name: logs_ingest
    auto_start: true
    keep_running: true
    processor:
      - json_indexing:
          index_name: ".infini_logs"
          elasticsearch: "default"
          input_queue: "es_logs"
          idle_timeout_in_seconds: 10
          output_queue:
            name: "es_logs_requests"
            label:
              tag: "metrics"
          worker_size: 1
          bulk_size_in_mb: 10
  - name: metrics_ingest
    auto_start: true
    keep_running: true
    processor:
      - json_indexing:
          index_name: ".infini_metrics"
          elasticsearch: "default"
          input_queue: "metrics"
          output_queue:
            name: "metrics_requests"
            label:
              tag: "metrics"
          worker_size: 1
          bulk_size_in_mb: 10
  - name: consume-metrics_requests
    auto_start: true
    keep_running: true
    processor:
      - bulk_indexing:
          bulk:
            compress: true
            batch_size_in_mb: 10
            batch_size_in_docs: 5000
          consumer:
            fetch_max_messages: 100
          queues:
            type: indexing_merge
          when:
            cluster_available: [ "default" ]

agent:
  major_ip_pattern: "192.*"
  labels:
    env: dev
  tags:
    - linux
    - x86
    - es7
    - v7.5

path.data: data
path.logs: log

agent.manager.endpoint: http://localhost:9000