path.data: data
path.logs: log

metrics:
  enabled: true
  major_ip_pattern: "192.*"
  queue: metrics
  labels:
    env: dev
  tags:
    - linux
    - x86
    - es7
    - v7.5
  network:
    enabled: true
    summary: true
    details: true
#    interfaces:
#      - en0
  memory:
    metrics:
      - swap
      - memory
  disk:
    metrics:
      - ioqs
      - throughput
  cpu:
    metrics:
      - idle
      - system
      - user
      - iowait
      - load
  elasticsearch:
    enabled: true
    node_stats: true
    index_stats: true

elasticsearch:
  - name: dev
    enabled: true
    schema: http
    monitored: true
    hosts:
      - 127.0.0.1:9200
#      - 192.168.3.188:9299
#  - name: 714
#    enabled: true
#    schema: http
#    monitored: true
#    hosts:
#      - 192.168.3.188:9206

pipeline:
  - name: metrics_ingest
    auto_start: true
    keep_running: true
    processor:
      - json_indexing:
          index_name: ".infini_metrics"
          elasticsearch: "714"
          input_queue: "metrics"
          worker_size: 1
          bulk_size_in_mb: 10

modules:
  - name: diagnostics
    enabled: true
    path: "/Users/medcl/Sync/INFINI/2022/1.28-观安诊断包/local-diagnostics-20220128-114946"
#    path: "/Users/medcl/Sync/INFINI/2021/10.12-Apollo 诊断包/local-diagnostics-20211011-164925"
#    path: "/Users/medcl/Sync/INFINI/2022/1.26-Apollo analysis result/api-diagnostics-20220123-000329"
    cluster_id: c7ogiq0vi074cnnnoo70
#    node_stats: true
#    index_stats: true
    shard_stats: true

console:
  name: dev
  host: 192.168.3.201
  port: 9000
  tls: false

filter:
 - get_cache:
 - bulk_reshuffle:
   when:
   contains:
   _ctx.request.path: /_bulk
   elasticsearch: dev
   level: node
   fix_null_id: true
 - set_cache: